apiVersion: v1
kind: Secret
metadata:
  name: image-repository-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "virtual-gsm-gateway-chart.labels" . | nindent 4 }}
type: Opaque
data:
  repository: {{ .Values.image.repository | b64enc | quote }}