apiVersion: v1
kind: Service
metadata:
  name: {{ include "virtual-gsm-gateway-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "virtual-gsm-gateway-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    {{- include "virtual-gsm-gateway-chart.selectorLabels" . | nindent 4 }}