apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "virtual-gsm-gateway-chart.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "virtual-gsm-gateway-chart.labels" . | nindent 4 }}